services:
  reverse-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      DISABLE_IPV6: 'true'
      X_FRAME_OPTIONS: "sameorigin"
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - odoo17
      - proxy
  
  odoo17:
    image: odoo:17.0
    container_name: odoo17
    restart: unless-stopped
    links:
      - db:db   
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./srv/odoo17-data:/var/lib/odoo
      - ./srv/config:/etc/odoo
      - ./srv/addons:/mnt/extra-addons
    networks:
      - odoo17

  db:
    image: postgres:17.0
    container_name: db
    restart: unless-stopped       
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - odoo17  

networks:
  odoo17:
  proxy:
    external: true